### ISSUE TITLE
k-Nearest Neighbor (kNN) is not k-Means

### ISSUE THREAD

**Issue by mirzaalimm** [AbhinavUtkarsh/Image-Segmentation#1]
Dear, Abhinav Utkarsh.

I found that your information in README.md doesn't match your code. I think you are confused between kNN and k-Means.

Regards.

**Comment by AbhinavUtkarsh** [comment]
Hey!
I just saw this, thanks for pointing it out, I misunderstood it back then!

Cheers!
Abhi
